(print
  (letrec* (
    (T (list 'T))
    (F (list 'F))
    (MkUnit (list 'MkUnit))
    (not_TT (lambda (x)
      (case (car x)
        ((T) F)
        ((F) T))))
    (main (not_TT (letrec* ((_casefun0 (lambda (x)
      (case (car x)
        ((F) MkUnit)
        ((T) F)))))
      (_casefun0 (not_TT F)))))
  )
    main))
(newline)
