(require-extension matchable)
(define Type '(Type))
(define (number->peano z s i) (if (= i 0) (list z) (list s (number->peano z s (- i 1)))))
(define (rts-arg-peano z s i) (number->peano z s (string->number (list-ref (command-line-arguments) i))))
(define (rts-arg-read i) (read (open-input-string (list-ref (command-line-arguments) i))))
(print
  (letrec* (
    (N `(N))
    (Z `(Z))
    (S (lambda (_x0)
      `(S ,_x0)))
    (plus (lambda (_e0)
      (lambda (_e1)
        (match (list _e0 _e1)
          ((('Z) m)
            m)
          ((('S n) m)
            (S ((plus n) m)))))))
    (main (letrec* ((pred (lambda (_e0)
      (match (list _e0)
        ((('Z))
          Z)
        ((('S n))
          n)))))
      ((plus (S (S Z))) (S (S (S Z))))))
  )
    main))
