(print
  (letrec* (
    (Tuple (lambda (x)
      (lambda (y)
        (lambda (z)
          (lambda (w)
            (list 'Tuple x y z w))))))
    (Bool (list 'Bool))
    (T (list 'T))
    (F (list 'F))
    (Mool (list 'Mool))
    (Q (list 'Q))
    (W (list 'W))
    (f (lambda (x)
      (case (car x)
        ((T) Bool)
        ((F) Bool)
        ((Q) Mool)
        ((W) Mool))))
    (main ((((Tuple (f T)) (f F)) (f Q)) (f W)))
  )
    main))
(newline)
