(print
  (letrec (
    (A (list 'A))
    (B (list 'B))
    (Op (lambda (x)
      (lambda (y)
        (list 'Op x y))))
    (id (lambda (x)
      x))
    (const_A A)
    (f (lambda (g)
      (lambda (z)
        (lambda (h)
          ((Op (g z)) h)))))
    (main (((f id) B) const_A))
  )
    main))
(newline)
