(require-extension matchable)
(print
  (letrec* (
    (T (list 'T))
    (F (list 'F))
    (P (lambda (x)
      (lambda (y)
        (list 'P x y))))
    (fst (lambda (_e0)
      (match (list _e0)
        [(('P l r))
          l])))
    (snd (lambda (_e0)
      (match (list _e0)
        [(('P l r))
          r])))
    (and (lambda (_e0)
      (lambda (_e1)
        (match (list _e0 _e1)
          [(('T) y)
            y]
          [(('F) y)
            F]))))
    (main ((and (fst ((P T) F))) (snd ((P F) T))))
  )
    main))
