(print
  (letrec* (
    (Q (list 'Q))
    (W (list 'W))
    (T (list 'T))
    (F (list 'F))
    (not_TT (lambda (x)
      (case (car x)
        ((T) F)
        ((F) T))))
    (mot (lambda (m)
      (case (car m)
        ((Q) W)
        ((W) Q))))
    (invert (lambda (t)
      (lambda (x)
        (case (car t)
          ((T) (not_TT x))
          ((F) (mot x))))))
    (main ((invert F) Q))
  )
    main))
