(require-extension matchable)
(print
  (letrec* (
    (Z (list 'Z))
    (S (lambda (n)
      (list 'S n)))
    (VNil (list 'VNil))
    (VCons (lambda (xs)
      (list 'VCons xs)))
    (vlen (lambda (_e0)
      (lambda (_e1)
        (match (list _e0 _e1)
          [(_ ('VNil))
            Z]
          [(('S n) ('VCons xs))
            (S ((vlen n) xs))]))))
    (testVec (VCons (VCons VNil)))
    (main ((vlen (S (S Z))) testVec))
  )
    main))
