(print
  (letrec (
    (Z (list 'Z))
    (S (lambda (n)
      (list 'S n)))
    (VNil (list 'VNil))
    (VCons (lambda (xs)
      (list 'VCons xs)))
    (vlen (lambda (xs)
      (case (car xs)
        ((VNil) Z)
        ((VCons) (let* (
          (_args-xs_ (cdr xs))
          (xs_ (car _args-xs_))
        )
          (S (vlen xs_)))))))
    (testVec (VCons (VCons VNil)))
    (main (vlen testVec))
  )
    main))
(newline)
