(print
  (letrec* (
    (subst (error "NOT IMPLEMENTED"))
    (T (list 'T))
    (F (list 'F))
    (Nil (list 'Nil))
    (Cons (lambda (x)
      (lambda (xs)
        (list 'Cons x xs))))
    (RNil (list 'RNil))
    (RSnoc (lambda (x)
      (lambda (rxs)
        (list 'RSnoc x rxs))))
    (rev_ (error "NOT IMPLEMENTED"))
    (rev (lambda (xs)
      ((rev_ RNil) xs)))
    (reverse_ (error "NOT IMPLEMENTED"))
    (reverse_TT (lambda (xs)
      (reverse_ (rev xs))))
    (main (reverse_TT ((Cons T) ((Cons F) ((Cons T) ((Cons F) Nil))))))
  )
    main))
