(require-extension matchable)
(print
  (letrec* (
    (True (list 'True))
    (False (list 'False))
    (Z (list 'Z))
    (S (lambda (_x0)
      (list 'S _x0)))
    (Even (list 'Even))
    (Odd (list 'Odd))
    (fun (letrec* (
      (even (lambda (_e0)
        (match (list _e0)
          [(('Z))
            True]
          [(('S n))
            ((fun Odd) n)])))
      (odd (lambda (_e0)
        (match (list _e0)
          [(('Z))
            False]
          [(('S m))
            ((fun Even) m)])))
    )
      (lambda (tag)
        (letrec* ((f (lambda (_e0)
          (match (list _e0)
            [(('Even))
              even]
            [(('Odd))
              odd]))))
          (f tag)))))
    (even (fun Even))
    (main (even (S (S (S (S (S (S (S (S Z))))))))))
  )
    main))
