(print
  (letrec* (
    (True (list 'True))
    (False (list 'False))
    (Z (list 'Z))
    (S (lambda (_x0)
      (list 'S _x0)))
    (Even (list 'Even))
    (Odd (list 'Odd))
    (fun (letrec* (
      (even (error "NOT IMPLEMENTED"))
      (odd (error "NOT IMPLEMENTED"))
    )
      (lambda (tag)
        (letrec* ((f (error "NOT IMPLEMENTED")))
          (f tag)))))
    (even (fun Even))
    (main (even (S (S (S (S (S (S (S (S Z))))))))))
  )
    main))
